configs = ({
               "name": "sina",
               "base_url": "https://portal.sina.com.hk/",
               "language": "zh",
               "target_categories": ["category/news-hongkong/", "category/news-china/", "category/news-intl/",
                                     "category/finance/"],
               "news_card_identifier": "article,single-article",
               "headline_identifier": "h1.entry-title",
               "datetime_identifier": "time.entry-date",
               "content_identifier": "div.entry-content",
               "is_debug": True
           },
           {
               "name": "hket",
               "base_url": "https://inews.hket.com/",
               "language": "zh",
               "target_categories": ["sran001/全部"],
               "news_card_identifier": "div.template-default div.template_item.hket-col-xs-60",
               "headline_identifier": "h1.main-title",
               "datetime_identifier": "div.below-headline-area div.publish-date-time",
               "content_identifier": "div.content",
               "is_debug": True
           },
           {
               "name": "hk01",
               "base_url": "https://www.hk01.com/",
               "language": "zh",
               "target_categories": ["channel/2/社會新聞", "channel/364/即時中國", "channel/19/即時國際",
                                     "channel/396/財經快訊"],
               "news_card_identifier": "div.content-card__main",
               "headline_identifier": "#articleTitle",
               "datetime_identifier": "time",
               "content_identifier": "div.article-grid__content-section",
               "is_debug": True
           },
           {
               "name": "std",
               "base_url": "https://std.stheadline.com/",
               "language": "zh",
               "target_categories": ["realtime/hongkong/即時-港聞", "realtime/international/即時-國際",
                                     "realtime/china/即時-中國",
                                     "realtime/finance/即時-財經"],
               "news_card_identifier": "div.media.heading-4",
               "headline_identifier": "h1",
               "datetime_identifier": "article.content span.date",
               "content_identifier": "section",
               "is_debug": True
           },
           {
               "name": "stheadline",
               "base_url": "https://www.stheadline.com/",
               "language": "zh",
               "target_categories": ["news/港聞", "china/中國", "world/國際", "finance/財經"],
               "news_card_identifier": "div.news-block",
               "headline_identifier": "div.article-title h1",
               "datetime_identifier": "div.time span",
               "content_identifier": "article",
               "is_debug": True
           },
           {
               "name": "mingpao",
               "base_url": "https://news.mingpao.com/",
               "language": "zh",
               "target_categories": ["ins/港聞/section/20240412/s00001", "ins/兩岸/section/20240412/s00004",
                                     "ins/國際/section/20240412/s00005"],
               "news_card_identifier": "div.contentwrapper",
               "headline_identifier": "h1",
               "datetime_identifier": "span.time",
               "content_identifier": "article",
               "is_debug": True
           },
           {
               "name": "am730",
               "base_url": "https://www.am730.com.hk/",
               "language": "zh",
               "target_categories": ["本地", "國際", "中國", "財經"],
               "news_card_identifier": "div.newsitem",
               "headline_identifier": "h1.article__head-title",
               "datetime_identifier": "div.article__head-time",
               "content_identifier": "div.article__body",
               "is_debug": True
           },
           {
               "name": "oncc",
               "base_url": "https://hk.on.cc/",
               "language": "zh",
               "target_categories": ["hk/news/index.html", "hk/cnnews/index.html", "hk/intnews/index.html",
                                     "hk/finance/index.html"],
               "news_card_identifier": "div.focus",
               "headline_identifier": "div.topHeadline",
               "datetime_identifier": "span.datetime",
               "content_identifier": "div.breakingNewsContent",
               "is_debug": True
           },
           {
               "name": "now",
               "base_url": "https://news.now.com/",
               "language": "zh",
               "target_categories": ["home/local", "home/international", "home/finance"],
               "news_card_identifier": "a.newsWrap",
               "headline_identifier": "h1.newsTitle",
               "datetime_identifier": "time.published",
               "content_identifier": "div.newsLeading",
               "is_debug": True
           },
           {
               "name": "hkej",
               "base_url": "http://www.hkej.com/",
               "language": "zh",
               "target_categories": ["instantnews/hongkong", "instantnews/china", "instantnews/international"],
               "news_card_identifier": "div.hkej_toc_listingAll_news2_2014",
               "headline_identifier": "h1.article-title",
               "datetime_identifier": "span.date",
               "content_identifier": "div#article-content",
               "is_debug": True
           },
           {
               "name": "tvb",
               "base_url": "https://news.tvb.com/",
               "language": "zh",
               "target_categories": ["tc/local", "tc/greaterchina", "tc/world", "tc/finance"],
               "news_card_identifier": "div.BigNewsContainer",
               "headline_identifier": "h1",
               "datetime_identifier": "div.entryCateInfo",
               "content_identifier": "h6.descContainer",
               "is_debug": True
           },
           {
               "name": "rthk",
               "base_url": "https://news.rthk.hk/",
               "language": "zh",
               "target_categories": ["rthk/ch/latest-news/local.htm", "rthk/ch/latest-news/greater-china.htm",
                                     "rthk/ch/latest-news/world-news.htm", "rthk/ch/latest-news/finance.htm"],
               "news_card_identifier": "div.ns2-page",
               "headline_identifier": "h2.itemTitle",
               "datetime_identifier": "div.createddate",
               "content_identifier": "div.itemBody",
               "is_debug": True
           },
           {
               "name": "rthk",
               "base_url": "https://news.rthk.hk/",
               "language": "en",
               "target_categories": ["rthk/en/latest-news/local.htm", "rthk/en/latest-news/greater-china.htm",
                                     "rthk/en/latest-news/world-news.htm", "rthk/en/latest-news/finance.htm"],
               "news_card_identifier": "div.ns2-page",
               "headline_identifier": "h2.itemTitle",
               "datetime_identifier": "div.createddate",
               "content_identifier": "div.itemBody",
               "is_debug": True
           },
           {
               "name": "scmp",
               "base_url": "https://www.scmp.com/",
               "language": "en",
               "target_categories": ["hk", "asia", ""],
               "news_card_identifier": 'div[data-qa="Component-Container"]',
               "headline_identifier": 'h2[data-qa="ContentHeadline-Container"]',
               "datetime_identifier": 'time[data-qa="DefaultArticleDate-time"]',
               "content_identifier": 'div[data-qa="GenericArticle-Content"]',
               "is_debug": True
           },
           {
               "name": "wenweipo",
               "base_url": "https://www.wenweipo.com/",
               "language": "zh",
               "target_categories": ["immed/hongkong", "immed/inland", "immed/world"],
               "news_card_identifier": "div.story-item",
               "headline_identifier": "h1",
               "datetime_identifier": "time.publish-date",
               "content_identifier": "div.post-body",
               "is_debug": True
           },
           {
               "name": "takungpao",
               "base_url": "https://www.takungpao.com.hk/",
               "language": "zh",
               "target_categories": ["hongkong/", "mainland/", "international/", "finance/"],
               "news_card_identifier": "div.content",
               "headline_identifier": "h1.tkp_con_title",
               "datetime_identifier": "h2.tkp_con_author",
               "content_identifier": "div.tkp_content",
               "is_debug": True
           })
